version: '3'
services:
  
  postgres:
    container_name: postgres
    build:
      context: Postgres
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB_USERNAME=arg_value
        - POSTGRES_DB_PASSWORD=arg_value
    hostname: reminder.postgres
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    
  redis:
    container_name: redis
    build:
      context: Redis
      dockerfile: Dockerfile   
    hostname: reminder.redis
    image: redis
    restart: always
    ports:
      - 6379:6379
  
  reminder:
    container_name: reminder
    build:
      context: Reminder
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB_USERNAME=arg_value
        - POSTGRES_DB_PASSWORD=arg_value
        - JWT_SECRET=arg_value
    image: banderveloper/reminder
    hostname: reminder
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
    depends_on:
      - postgres
      - redis
    restart: on-failure
  
volumes:
  db_data: